### ISSUE TITLE
0.13.0 build failure

### ISSUE THREAD

**Issue by chenrui333** [alexpovel/srgn#106]
👋 trying to build the latest release, but run into some build issue. The error log is as below:

<details>
<summary>error build log</summary>

```
  warning: srgn@0.13.0: clang: error: no such file or directory: 'src/scoping/langs/tree_sitter_hcl/upstream/src/parser.c'
  warning: srgn@0.13.0: clang: error: no input files
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/10441887513/job/28913617832?pr=181589
relates to Homebrew/homebrew-core#181589

**Comment by alexpovel** [comment]
Thanks for your report!

This release requires `git submodule update --init`. Is that something the brew CI does/can do?

**Comment by alexpovel** [comment]
`0.13.1` should now work. I stopped using git submodules as part of #107 , the changes of which were released as part of #105 . Could you try again?

I reckon `0.13.0` will never build unless `git submodule update --init` is ran.

**Comment by chenrui333** [comment]
yeah, totally, thanks for the quick turnaround. 👍

**Comment by chenrui333** [comment]
Looks like 0.13.1 release, the test behavior got changed for this

```
    test_string = "Hide ghp_th15 and ghp_th4t"
    assert_match "Hide * and *", pipe_output("#{bin}/srgn '(ghp_[[:alnum:]]+)' '*'", test_string)
```

diff output

```diff
-    assert_match "Hide ******** and ********", pipe_output("#{bin}/srgn '(ghp_[[:alnum:]]+)' '*'", test_string)
+    assert_match "Hide * and *", pipe_output("#{bin}/srgn '(ghp_[[:alnum:]]+)' '*'", test_string)
```

is that desired?

**Comment by alexpovel** [comment]
Yes! Unfortunately, looks like Homebrew happened to pick one of the few breaking changes as a test case. Sorry! It will need to be adjusted. 

Is there a way to just run `cargo test`? That will always be reliable, and covers large areas of the CLI surface (aka they’re pretty end to end). 

If no, feel free to pick a test case from the README. They’re all part of unit tests and guaranteed to work.

Otherwise, I can come up with a couple tests for you to use?

**Comment by alexpovel** [comment]
Hey @chenrui333 , this is good to close right? I see `0.13.1` built.
