### ISSUE TITLE
Add support for terraform

### ISSUE THREAD

**Issue by kishaningithub** [alexpovel/srgn#74]
It would be great to have a support for terraform's HCL language

https://developer.hashicorp.com/terraform/language/syntax/configuration

**Comment by alexpovel** [comment]
Hi! Thanks for your report. Great you mention HCL, as I just recently added support for it in 814a592dbc3e446c6751bc2ab40b9e83337c726b .

The change is in `main` and `cargo build --release` will get it for you locally. Otherwise, it will land in the next release soon, which happens once #72 is merged.

Perhaps you can have a look at the implemented functionality and let me know of anything else you'd like to see.

**Comment by alexpovel** [comment]
Hi!

HCL support was expanded since 814a592 and is now available in the latest release. For now, that release is probably fetched easiest by [downloading one of the compiled binaries](https://github.com/alexpovel/srgn/releases/tag/srgn-v0.13.0).
